# output: add.o sub.o mul.o div.o
# 	gcc add.o sub.o mul.o div.o -o output

add.o: add.c
	gcc add.c -c

sub.o: sub.c
	gcc sub.c -c

mul.o: mul.c
	gcc mul.c -c

div.o: div.c
	gcc div.c -c

# clean:
# 	rm *.o output

# run:
# 	./output